backend:
  name: github
  repo: rodinshrestha/kitchen-v2
  branch: main

publish_mode: editorial_workflow
media_folder: "static/uploads"
public_folder: /uploads

collections:
  - name: "starter_salad"
    label: "Starter and Salad"
    folder: "/content/kitchen_menu/starter_salad"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "momo"
    label: "MoMo - Steamed Dumplings"
    folder: "/content/kitchen_menu/momo"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "curry_dishes"
    label: "Curry Dishes"
    folder: "/content/kitchen_menu/curry_dishes"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "tandoori"
    label: "Tandoori"
    folder: "/content/kitchen_menu/tandoori"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "tika_masala"
    label: "Tika Masala"
    folder: "/content/kitchen_menu/tika_masala"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "sides"
    label: "Sides"
    folder: "/content/kitchen_menu/sides"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  #######################
  # Drinks Menu list
  #######################

  - name: "sparkling_wines"
    label: "Sparkling Wines"
    folder: "/content/drinks_menu/sparkling_wines"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "white_wines"
    label: "White Wines"
    folder: "/content/drinks_menu/white_wines"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "red_wines"
    label: "Red Wines"
    folder: "/content/drinks_menu/red_wines"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "beer"
    label: "Beer"
    folder: "/content/drinks_menu/beer"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "beverages"
    label: "Beverages"
    folder: "/content/drinks_menu/beverages"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }

  - name: "gallery"
    label: "Gallery"
    folder: "/content/gallery"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }

  #######################
  # Website Settings
  #######################

  - name: "settings"
    label: "Settings"
    files:
      # Website Settings
      - label: "Website Settings"
        name: "website_settings"
        file: "content/settings/settings.json"
        fields:
          - label: "Home Page Title"
            name: "home_page_title"
            widget: "string"

          - label: "Site Logo"
            name: "site_logo"
            widget: "image"

          - label: "title logo"
            name: "title_logo"
            widget: image

          - label: "Footer Text"
            name: "footer_text"
            widget: "string"

          - label: "Phone Number"
            name: "phone_number"
            widget: "string"

          - label: "Email"
            name: "email"
            widget: "string"

          - label: "Hero Banner Text"
            name: "hero_banner_text"
            widget: "text"

          - label: "Lunch Time"
            name: "lunch_time"
            widget: "string"

          - label: "Lunch last seated Time"
            name: "lunch_last_seated_time"
            widget: "string"

          - label: "Dinner Time"
            name: "dinner_time"
            widget: "string"

          - label: "Dinner last seated Time"
            name: "dinner_last_seated_time"
            widget: "string"

          - label: "Story"
            name: "story_content"
            widget: "markdown"

          - label: "Reservation Link"
            name: "reservation_link"
            widget: "string"

          - label: "Yelp Link"
            name: "yelp_link"
            widget: "string"

          - label: "Facebook Link"
            name: "facebook_link"
            widget: "string"

          - label: "Instagram Link"
            name: "instagram_link"
            widget: "string"

      # Kitchen Menu Settings
      - label: "Kitchen Menu Helper"
        name: "kitchen_menu_helper"
        file: "content/settings/kitchen_menu_helper.json"
        fields:
          - label: "Curry Dishes Description"
            name: "curry_dishes_description"
            widget: "string"

          - label: "Momo Description"
            name: "momo_description"
            widget: "string"

          - label: "Sides Description"
            name: "sides_description"
            widget: "string"

          - label: "Starter Salad Description"
            name: "starter_salad_description"
            widget: "string"

          - label: "Tandoori Description"
            name: "tandoori_description"
            widget: "text"

          - label: "Tika Masala Description"
            name: "tika_masala_description"
            widget: "string"

      # Drinks Menu Settings
      - label: "Drinks Menu Helper"
        name: "drink_menu_helper"
        file: "content/settings/drinks_menu_helper.json"
        fields:
          - label: "Beer Description"
            name: "beer_description"
            widget: "string"

          - label: "Beverages Description"
            name: "beverages_description"
            widget: "string"

          - label: "Red Wine Description"
            name: "red_wine_description"
            widget: "string"

          - label: "Sparkling Wine Description"
            name: "sparkling_wine_description"
            widget: "string"

          - label: "White Wine Description"
            name: "white_wine_description"
            widget: "text"

      # Menu List Helper
      - label: "Menu List Helper"
        name: "menu_list_helper"
        file: "content/settings/menu_list_helper.json"
        fields:
          - label: "Menu Footer Description"
            name: "menu_footer_description"
            widget: "string"

          - label: "Menu Footer Address"
            name: "menu_footer_address"
            widget: "markdown"

          - label: "Menu Service Charge Description"
            name: "menu_service_charge_description"
            widget: "string"

  #######################
  # Blog Details
  #######################

  - name: "blog"
    label: "Blog"
    folder: "/content/blog"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }

  #######################
  # Everest trek details
  #######################

  - name: "everest-trek"
    label: "Everest Base Camp Trek"
    files:
      - label: Everest Base Camp Trek
        name: everest-base-camp-description
        file: "/content/everest_base_camp_trek/everest-base-camp-description.md"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Description", name: "description", widget: "markdown" }

  # #######################
  # Page SEO
  # #######################

  - name: "search-engine-optimization"
    label: "Search Engine Optimization(SEO)"
    files:
      # Home Page SEO
      - label: Home Page SEO
        name: home-page-seo
        file: "content/seo/home-page.json"
        fields:
          - label: "Seo Title"
            name: "seo_title"
            widget: "string"

          - label: "Meta Description"
            name: "meta_description"
            widget: "string"

          - label: "Meta Keywords"
            name: "meta_keywords"
            widget: "string"

      # About Us SEO
      - label: About US SEO
        name: about-us-seo
        file: "content/seo/about-us-seo.json"
        fields:
          - label: "Seo Title"
            name: "seo_title"
            widget: "string"

          - label: "Meta Description"
            name: "meta_description"
            widget: "string"

          - label: "Meta Keywords"
            name: "meta_keywords"
            widget: "string"

      # Contact us SEO
      - label: Contact US SEO
        name: contact-us-seo
        file: "content/seo/contact-us-seo.json"
        fields:
          - label: "Seo Title"
            name: "seo_title"
            widget: "string"

          - label: "Meta Description"
            name: "meta_description"
            widget: "string"

          - label: "Meta Keywords"
            name: "meta_keywords"
            widget: "string"

      # Everest Trek SEO
      - label: Everest Trek SEO
        name: everest-trek-seo
        file: "content/seo/everest-trek-seo.json"
        fields:
          - label: "Seo Title"
            name: "seo_title"
            widget: "string"

          - label: "Meta Description"
            name: "meta_description"
            widget: "string"

          - label: "Meta Keywords"
            name: "meta_keywords"
            widget: "string"

      # Experience SEO
      - label: Experience Page SEO
        name: experience-page-seo
        file: "content/seo/experience-page-seo.json"
        fields:
          - label: "Seo Title"
            name: "seo_title"
            widget: "string"

          - label: "Meta Description"
            name: "meta_description"
            widget: "string"

          - label: "Meta Keywords"
            name: "meta_keywords"
            widget: "string"

      # Gallery Page SEO
      - label: Gallery Page SEO
        name: gallery-page-seo
        file: "content/seo/gallery-page-seo.json"
        fields:
          - label: "Seo Title"
            name: "seo_title"
            widget: "string"

          - label: "Meta Description"
            name: "meta_description"
            widget: "string"

          - label: "Meta Keywords"
            name: "meta_keywords"
            widget: "string"

      # Menu Page SEO
      - label: Menu Page SEO
        name: menu-page-seo
        file: "content/seo/menu-page-seo.json"
        fields:
          - label: "Seo Title"
            name: "seo_title"
            widget: "string"

          - label: "Meta Description"
            name: "meta_description"
            widget: "string"

          - label: "Meta Keywords"
            name: "meta_keywords"
            widget: "string"
